artifact_location: /workspaces/mlops-zoomcamp/02-experiment-tracking/homework/sqlite/mlflow.db/0
creation_time: 1716831326994
experiment_id: '0'
last_update_time: 1716831326994
lifecycle_stage: active
name: Default
